version: '3.10'
services:
  mysql:
    image: mysql:8.0.33
    # deploy:
    #   resources:
    #     limits:
    #       cpus: "0.3"
    #       memory: "1G"
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootroot
      MYSQL_DATABASE: mertautodb
      MYSQL_USER: mertauto
      MYSQL_PASSWORD: mertauto123456
      MYSQL_MAX_ALLOWED_PACKET: 128M
      TZ: UTC
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init/init.sql:/docker-entrypoint-initdb.d/1-init.sql
      - ./mysql-init/schema.sql:/docker-entrypoint-initdb.d/2-schema.sql
      - ./mysql-init/data.sql:/docker-entrypoint-initdb.d/3-data.sql
      - ./mysql-init/mysql.cnf:/etc/mysql/conf.d/mysql.cnf:ro
    networks:
      - app-network
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --default-authentication-plugin=mysql_native_password
      --max_allowed_packet=128M
      --bind-address=0.0.0.0
      --secure-file-priv=/var/lib/mysql-files
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "mertauto", "-pmertauto123456"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    # deploy:
    #   resources:
    #     limits:
    #       cpus: "0.4"
    #       memory: "1G"
    container_name: spring-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/mertautodb?allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=mertauto
      - SPRING_DATASOURCE_PASSWORD=mertauto123456
      - SPRING_DEVTOOLS_RESTART_ENABLED=true
      - SPRING_DEVTOOLS_LIVERELOAD_ENABLED=true
    volumes:
      - ./backend/src:/app/src
      - ./backend/pom.xml:/app/pom.xml
      - backend_maven_cache:/root/.m2
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    # deploy:
    #   resources:
    #     limits:
    #       cpus: "0.3"
    #       memory: "1G"
    container_name: nextjs-frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_BACKEND_API_URL=http://spring-backend:8080
      - NEXT_PUBLIC_API_URL=http://localhost:8080
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=NQOSd8J/wnueoxrzwc9BzoSfxvn5vvT9d+pGowghpUA=
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  mysql_data:
  backend_maven_cache:

networks:
  app-network:
    driver: bridge