version: '3.15'
services:
  mysql:
    image: mysql:8.0.33
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "1G"
        reservations:
          cpus: "0.2"
          memory: "512M"
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootroot
      MYSQL_DATABASE: mertautodb
      MYSQL_USER: mertauto
      MYSQL_PASSWORD: mertauto123456
      MYSQL_MAX_ALLOWED_PACKET: 128M
      TZ: UTC
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init/init.sql:/docker-entrypoint-initdb.d/1-init.sql
      - ./mysql-init/schema.sql:/docker-entrypoint-initdb.d/2-schema.sql
      - ./mysql-init/data.sql:/docker-entrypoint-initdb.d/3-data.sql
      - ./mysql-init/mysql.cnf:/etc/mysql/conf.d/mysql.cnf:ro
    networks:
      - app-network
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --default-authentication-plugin=mysql_native_password
      --max_allowed_packet=128M
      --bind-address=0.0.0.0
      --secure-file-priv=/var/lib/mysql-files
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "mertauto", "-pmertauto123456"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile.prod
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "300M"
    container_name: spring-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/mertautodb?allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=mertauto
      - SPRING_DATASOURCE_PASSWORD=mertauto123456
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - app-network

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.prod
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "1G"
        reservations:
          memory: "512M"
    container_name: nextjs-frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_BACKEND_API_URL=http://spring-backend:8080
      - NEXT_PUBLIC_API_URL=https://mertautogarage.com
      - NEXTAUTH_URL=https://mertautogarage.com
      - NEXTAUTH_SECRET=NQOSd8J/wnueoxrzwc9BzoSfxvn5vvT9d+pGowghpUA=
      - NODE_ENV=production
      - NEXTAUTH_URL_INTERNAL=http://nextjs-frontend:3000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s    
    depends_on:
      - backend
    networks:
      - app-network

  nginx:
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "100M"
    image: nginx:stable
    container_name: nginx-prod
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/logs:/var/log/nginx
      - ./certbot/www:/var/www/certbot
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      frontend:
        condition: service_healthy
      backend:
        condition: service_healthy
    networks: 
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - /etc/letsencrypt:/etc/letsencrypt
    command: certonly --webroot -w /var/www/certbot --force-renewal --email gurkay.basyigit@gmail.com -d mertautogarage.com -d www.mertautogarage.com --agree-tos

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge