# Development image for hot reload
FROM openjdk:23-jdk-slim
WORKDIR /app

# Maven yükleme
RUN apt-get update && \
    apt-get install -y maven && \
    apt-get clean

# Add package.json only
COPY pom.xml .

# Expose port
EXPOSE 8080

# Run in development mode with devtools for hot reloading
CMD ["mvn", "spring-boot:run", "-Dspring-boot.run.jvmArguments='-Dspring.devtools.restart.enabled=true -Dspring.devtools.restart.poll-interval=1000 -Dspring.devtools.restart.quiet-period=400'"]