package com.template.backend.entities;

public enum ERole {
  ROLE_USER,
  ROLE_MANAGER,
  ROLE_ADMIN,
  ROLE_SALESPERSON,
  ROLE_EDITOR,
  ROLE_SHIPPER,
  ROLE_ACCOUNTING,
  ROLE_SUPERVISOR,
  ROLE_TECHNICIAN,
  ROLE_TEACHER,
  ROLE_STUDENT,
  ROLE_ASSISTANT,
  ROLE_RECEPTIONIST,
  ROLE_RESEARCHER,
  ROLE_REPORTER,
  ROLE_REVIEWER
}
